name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Check version matches tag
        run: |
          python - <<'PY'
          import tomllib, os, sys
          with open("pyproject.toml","rb") as f:
              ver = tomllib.load(f)["project"]["version"]
          tag = os.environ["GITHUB_REF_NAME"].lstrip("v")
          if ver != tag:
              print(f"Version mismatch: pyproject={ver} tag={tag}")
              sys.exit(1)
          print(f"Version OK: {ver}")
          PY

      - name: Build sdist/wheel
        run: |
          pip install -U build twine
          python -m build
          python -m twine check dist/*

      - name: "Debug: list and peek METADATA"
        run: |
          python - <<'PY'
          import glob, zipfile, os
          for fn in glob.glob("dist/*.whl"):
              print("==>", fn, os.path.getsize(fn), "bytes")
              with zipfile.ZipFile(fn) as z:
                  metas = [n for n in z.namelist() if n.endswith("METADATA")]
                  print("METADATA paths:", metas)
                  if metas:
                      print(z.read(metas[0]).decode("utf-8","replace")[:400])
          PY

      - name: Publish to PyPI (API token)
        if: ${{ vars.PUBLISH_TO_PYPI == 'true' }}
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          packages-dir: dist
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
          verify-metadata: false
