name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Build sdist/wheel
        run: |
          pip install build
          python -m build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish-pypi:
    needs: build
    # gated — won't run until you set this repo variable to 'true'
    if: ${{ vars.PUBLISH_TO_PYPI == 'true' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write   # required if you later use Trusted Publishing
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Publish to PyPI (trusted publishing)
        uses: pypa/gh-action-pypi-publish@v1.9.0
        with:
          packages-dir: dist
          skip-existing: true
